#!/bin/bash
FILE=$1
LINE=${2:-1}

find_nvim_socket() {
	local path
	local dir
	local socket
	local socket_birth_time
	local oldest_socket=""
	local oldest_birth_time=""

	shopt -s nullglob
	for path in /tmp/nvim*; do
		if [[ -S $path ]]; then
			socket=$path
		elif [[ -d $path ]]; then
			for dir in "$path"/*; do
				[[ -d $dir ]] || continue

				for socket in "$dir"/*; do
					[[ -S $socket ]] || continue

					if nvim --server "$socket" --remote-expr '1' >/dev/null 2>&1; then
						socket_birth_time=$(stat -c '%W' "$socket") || continue
						[[ $socket_birth_time -gt 0 ]] || continue

						if [[ -z $oldest_birth_time || $socket_birth_time -lt $oldest_birth_time ]]; then
							oldest_birth_time=$socket_birth_time
							oldest_socket=$socket
						fi
					fi
				done
			done

			continue
		else
			continue
		fi

		if nvim --server "$socket" --remote-expr '1' >/dev/null 2>&1; then
			socket_birth_time=$(stat -c '%W' "$socket") || continue
			[[ $socket_birth_time -gt 0 ]] || continue

			if [[ -z $oldest_birth_time || $socket_birth_time -lt $oldest_birth_time ]]; then
				oldest_birth_time=$socket_birth_time
				oldest_socket=$socket
			fi
		fi
	done
	shopt -u nullglob

	[[ -n $oldest_socket ]] || return 1
	printf '%s\n' "$oldest_socket"

	return 0
}

NVIM_SOCKET=$(find_nvim_socket) || {
	printf 'No running nvim socket found\n' >&2
	exit 1
}

nvim --server "$NVIM_SOCKET" --remote-send "<C-\\><C-n>:e +$LINE $FILE<CR>"
