#!/bin/bash
WORKSPACE='workspace --no-auto-back-and-forth'
BRAVE='flatpak run com.brave.Browser --profile-directory="Default"'
MY_EMAIL_APP="$BRAVE --app-id=faolnafnngnfdaknnbpnkhgohbobgegn"
SUPPORT_APP="$MY_EMAIL_APP --app=https://outlook.office.com/mail/support@rtvision.com"
TEAMS_APP="$BRAVE --app-id=cifhbcnohmdccbgoicgdjpfamggdegmo"

# need to sleep in between workspace msgs otherwise
# things can open up in the wrong workspace
i3-msg "$WORKSPACE 1; append_layout ~/.i3/workspaces/terminal.json;"
i3-msg 'exec "xterm -en UTF-8 -u8 -e \"bash -l -c ~/.xterm_startup; bash\""'
sleep 0.2
i3-msg "$WORKSPACE 2; append_layout ~/.i3/workspaces/browser.json;"
i3-msg "exec $BRAVE https://app.kalvens.rtvision.com"
sleep 3
i3-msg "$WORKSPACE 3; append_layout ~/.i3/workspaces/communications.json"
sleep 0.2
# Spotify and teams have issues when other stuff is
# opening so sleep between those two
i3-msg "exec flatpak run com.spotify.Client"
sleep 1
i3-msg "exec $TEAMS_APP"
sleep 0.2
i3-msg "exec $SUPPORT_APP"
# sleep just so my email is on top
sleep 0.2
i3-msg "exec $MY_EMAIL_APP"
